doggy/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include
from homepage import urls
from useraccount import urls
from pets import urls
from sitter import urls
from django.conf import settings
from django.conf.urls.static import static
from help import urls




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('useraccount/', include('useraccount.urls')),
    path('pets/', include('pets.urls')),
    path('sitter/', include('sitter.urls')),
    path('reservations/', include('reservations.urls')),
    path('help/', include('help.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'useraccount'

help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.send_email_help, name='send_email_help'), ]

homepage/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.home, name='home'),
 
]

pets/urls.py
from django.urls import path, include
from . import views

app_name = 'pet'



urlpatterns = [
    path('pets/',views.pets, name='pets'),
    # path('registro_pet/<int:user_id>',views.CreatePet.as_view(), name='pets_register'),
    path('registro_pett/<str:user>/',views.createPet, name='register'),
    

]

useraccount/urls.py
from django.urls import path, include
from .views import UserEditView, PwdChangeView, UserEditExtendedView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'useraccount'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login_doggy, name='login'),
    path('password', PwdChangeView.as_view(template_name='registration/password.html'),name='password'),
    path('pwdsuccess', views.pwdsuccess, name='pwdsuccess'),
    path('<int:pk>', views.assign_role, name='assign_role'),
    path('logout',views.logout_doggy,name='logout'),
    path('editpro', UserEditView.as_view(), name='editpro'),

    path('password', PwdChangeView.as_view(template_name='registration/password.html'), name='password'),
   # path('password_success', views.password_success, name='password_success'),
   # path('password_success', views.password_success, name='password_success'),
    #path('password_success', views.password_success, name='password_success'),
    path('editprofile/<int:pk>/', UserEditExtendedView.as_view(), name='editprofile'), 
   # path('create_profile', views.create_profile, name='create_profile'),

    
    
   

]

homepage/views.py
from django.shortcuts import render,redirect
from pets.models import  Pet
from sitter.models import Sitter
from django.contrib.auth.models import User


# Create your views here.
def home(request):
    
    user_role = "Invitado"
    
    result_set = Sitter.objects.filter(user_id=request.user.id)
    if result_set:
        user_role = "Cuidador"
    
    result_set = Pet.objects.filter(user_id=request.user.id) 
    if result_set:
        user_role = "Dueño"   
        
    return render(request, 'homepage/index.html', {'role': user_role })

homepage/templates/homepage/base.html
    {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <title>
    {% block title %}
    {% endblock %}
   </title> 
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="{% static 'JS/script.js' %}"></script>
    
</head>
 
<body>
    <div class= "mw-100">
  
  {% include "homepage/navbar.html" %}
  {% include "messages.html" %}
    {% block content %}

     <!-- LOGICA DE LAS DEMAS VISTAS -->

    {% endblock %}
    
  {% include "homepage/footer.html" %}
   </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>
</html>

homepage/templates/homepage/footer.html
{% load static %}
   <footer>
          <div class="container-fluid text-white p-5" style="background-color:#7591F0" >
            <div class="mx-auto">
            <!-- Doggy  menu-->
            <div class="row">
              <div class="col-md-4">
                <div class="mw-100">
                  <div class="text-left py-2">
                    <h5>Doggy</h5>
                  </div>
                <ul style="list-style: none; margin:0; padding: 0;">
                  <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'home' %}">Inicio</a></li>
	         <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'send_email_help' %}">Ayuda</a></li>

        {% if user.is_authenticated %}
         
          {% if 'Cuidador' in role %}
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'sitter_list' %}">Ver otros cuidadores</a></li>
	                   

          {% endif %}  
          
          {% if 'Dueño' in role %}
	
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'sitter_list' %}">Buscar cuidadores</a></li>
	  {% endif %}
         
          {% if 'Invitado' in role %}
          
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'sitter_list' %}">Buscar cuidadores</a></li>
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'create_sitter' user.id %}">Convertirse en cuidador</a></li>
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'pet:register' user.id  %}">Registrar canino</a></li>

	  {% endif %}  

        {% else %}
	  
	<li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'sitter_list' %}">Buscar cuidadores</a></li>
	
	<li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'useraccount:login' %}">Iniciar sesións</a></li>
	
      
             <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'useraccount:register' %}">Registrarme</a></li>
         
        

	{% endif %}
                </ul>
                </div>
              </div>
              <div class="col-md-4 ">
                <div class="text-left py-2">
                  <h5>Terminos y Condiciones</h5>
                  <h6 class="py-2">Politicas de privacidad</h6>
                </div>
                <div class="container-fluid ">
                  <!-- redes sociales -->
                  <div class="row">
                    <div class="col-4">
                      <a href="https://www.instagram.com/doggyoficial1820/"><img src="{% static 'img/icon-instagram.png' %}"> </a>
                   </div>
                    <div class="col-4">
                      <a href="#"><img src="{% static 'img/icon-facebook.png' %}"> </a>
                    </div>
                    <div class="col-4">
                      <a href="https://twitter.com/AppDoggy"><img src="{% static 'img/icon-twitter.png' %}"> </a>
                    </div>
                </div>
              </div>
          </div>
          <div class="col-md-4 text-left py-2">
            <h5>Descarga nuestra aplicacion</h5>
	    <a href="#"><img style= "max-width: 220px; padding: 5px;" src="{% static 'img/icon-google-play.png' %}"></a>
	    <a href="#"><img style= "max-width: 200px; padding: 5px;" src="{% static 'img/icon-apple-store.png' %}"></a>

          </div>
        </div>
           
      </footer>
    

homepage/templates/homepage/index.html
{% extends "homepage/base.html" %}
{% load static %}
{% block title %}
  Doggy-app
{% endblock %}
{% block content %}


	      
  <img class="img-fluid h-100 w-100" src="{% static 'img/fondo-portada.jpg' %}" alt="">

      {% if user.is_authenticated %}
    <!--========================================================== -->
		<!-- Pantalla de Bienvenida-->
    <!--========================================================== -->
<div class="container h-100 mb-5" style="width: 80%;">

     <div class="row mt-4">
       <h3> Bienvenido/a <span style="color: #6b8cff;">{{user.username}}</span></h3>
    </div>

<div class="row mt-2 p-2">
	    <h5> Ya podés:</h5>
    </div>

    <div class="row mt-3">
      <div class="col-md-1 col-sm-12">
       <img class="p-2" src="{% static 'img/numero_1.png' %}">
      </div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
          <a class="nav-link" href="{% url 'create_sitter' user.id %}">
	<h5>Resgistrarte como cuidador/a</h5>
	    </a>
      </div>
      <div class="row py-2">
	  <p> Ofrecé servicio de hospedaje para recibir perros según tu disponibilidad y tarifa. Así podrán encontrarte y realizar reservas a través de Doggy.</p>
      </div>
</div>
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/numero_2.png' %}">

</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
          <a class="nav-link" href="{% url 'pet:register' user.id  %}">
	<h5>Registrar a tu perro</h5>
	    </a>
    </div>
  <div class="row py-2">
	<p>Acá podrás registrar a tu mascota, para que los cuidadores puedan conocer sus características al hacer tu reserva y puedan brindarle un servicio de acuerdo a sus necesidades.</p>
      </div>
</div>

<div class="col-md-1 col-sm-12">
	<img class="p-2" src="{% static 'img/numero_3.png' %}">
</div>

<div class="col-lg-3 col-sm-12">

  <div class="row p-2">
          <a class="nav-link" href="{% url 'sitter_list' %}">
	  <h5>Buscar hospedaje para tu perro</h5>
	    </a>
      </div>
    <div class="row py-2">
	<p>Encontrá al cuidador adecuado para tu perro y paga on-line para contar con la cobertura veterinaria.</p>
    </div>
</div>

</div>

</div>




        {% else %}
    <!--========================================================== -->
		<!-- ¿Cómo funciona? Y ¿ Por Qué Doggy?-->
    <!--========================================================== -->
  <div class="container h-100" style="width: 80%;">

    <div class="row mt-4 p-2">
	    <h3>¿Cómo funciona Doggy?</h3>
    </div>

    <div class="row mt-3">
      <div class="col-md-1 col-sm-12">
       <img class="p-2" src="{% static 'img/numero_1.png' %}">
      </div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Buscá</h5>
      </div>
      <div class="row p-2">
	  <p>Busca y contacta con cuidadores de confianza y con experiencia cerca de tí.</p>
      </div>
</div>
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/numero_2.png' %}">

</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Reservá</h5>
    </div>
  <div class="row p-2">
	<p>Encuentra al cuidador adecuado para tu perro y paga on-line para contar con la cobertura veterinaria.</p>
      </div>
</div>

<div class="col-md-1 col-sm-12">
	<img class="p-2" src="{% static 'img/numero_3.png' %}">
</div>

<div class="col-lg-3 col-sm-12">

  <div class="row">
	  <h5>Relajate</h5>
      </div>
    <div class="row">
	<p>Tu perro se divertirá y estará en familia y tú recibirás fotogradías regularmente.</p>
    </div>
</div>

</div>

</div>



  <div class="container" style="width: 80%;">

<div class="row mt-4 p-2">
	<h3>¿Por qué Doggy?</h3>
</div>

<div class="row mt-3">
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/huella.png' %}">
</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Beneficios para tu perro</h5>
      </div>
      <div class="row p-2">
	<ul>
	  <li>Atención personalizada en un hogar familiar</li>
	  <li>No más jaulas</li>
	  <li>Muchos paseos, juegos y mimos</li>

	</ul>	
      </div>
</div>
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/beneficio.png' %}">

</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Beneficios para vos</h5>
    </div>
  <div class="row p-2">
	<ul>
	  <li>+15.000 cuidadores evaluados por Doggy</li>
	  <li>Valoraciones y comentarios de otros propietarios de perros</li>
	</ul>	


      </div>
</div>

<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/tranquilidad.png' %}">
  
</div>

<div class="col-md-3 col-sm-12">

  <div class="row">
	  <h5>Tranquilidad</h5>
      </div>
    <div class="row">
	<ul>
	  <li>Cobertura veterinaria con cada reserva</li>
	  <li>Mensajes y pago seguro online</li>
	  <li>Actualizaciónes diarias de fotos y mensajes</li>

	</ul>	
    </div>
</div>
</div>
</div>

        {% endif %}
    <!--========================================================== -->
		<!-- Comentarios de usuarios -->
    <!--========================================================== -->
  <div class="container-fluid bg-dark p-5 min-vh-100">
    <div class="container row w-sm-100 w-lg-75 p-5 my-5">
      <div class="col-md-3 text-center">
      <img class="user-comment mt-4" src="{% static 'img/user1.png' %}">
      </div>
      <div class="col-md-9">
      <h5 class="font-weight-bold text-light p-4">Tomas Bravo de María Laura Montez</h5>
      <p class="text-light text-left">“Mejor imposible! Era la primera vez que utilizábamos la aplicación y a una cuidadora, María Laura es muy atenta en todo momento nos tuvo informados, con fotos y vídeos a la pequeña se la vio muy bien antendida. Estamos muy contentos con ella. Repetimos seguro.”</p> 
      </div>
    </div>
</div>
</div>

    <!--========================================================== -->
		<!-- Preguntas Frecuentes -->
    <!--========================================================== -->



  <div class="container p-4 my-5 min-vh-100 w-74">

<div class="mt-4 p-2 text-center">
  <h3 class="font-weight-bold">Preguntas Frecuentes (FAQ)</h3>
</div>
<ul>  <div class="p-2">
    <li><h5 class="font-weight-bold">¿Doggy es adecuado para mi perro?</h5> </li>	
      </div>
      <div>
	  <p class="text-justify">Creemos que todos los perros deberían ser cuidados por cuidadores cariñosos que les proporcionen atención personalizada, muchos paseos, tiempo de juego y mimos
	    <span id="points1">...</span>
  
	    <span id="moreText1" style="display: none;"> para proporcionarles el bienestar necesario. Para nosotros su felicidad es lo primero y promovemos constantemente dinámicas en ese mismo sentido. En el caso, por ejemplo de que un cuidador presente diversas puntuaciones negativas nuestroequipo se pondrá en contacto con él. </span>
	  <a onclick="toggleText1()" id="textButton1" class="link-dark read-more"> Leer más</a>
	</p>
      </div>

  <div class="p-2">
	<li><h5 class="font-weight-bold">¿Son seguros los cuidadores de Doggy?</h5></li>	
      </div>
      <div>
	<p class="text-justify">Nos comprometemos a proporcionar un entorno seguro para la comunidad Doggy. Todos los cuidadores pasan por un estricto proceso de selección con el equipo de confianza
	    <span id="points2">...</span>
  
	    <span id="moreText2" style="display: none;"> de nuestra empresa. Para dicha evaluación se deben cumplir diversos criterios que aseguran que cada uno de los cuidadores dispongan de la posibilidad de generar un entorno seguro para el perro que vayan a cuidar. </span>
	  <a onclick="toggleText2()" id="textButton2" class="link-dark read-more"> Leer más</a>
	</p>
      </div>


  <div class="p-2">
	<li><h5 class="font-weight-bold">¿Puedo conocer al cuidador antes de una reserva?</h5></li>	
      </div>
      <div class="">
	<p class=""text-justify>¡Por supuesto! Siempre recomendamos organizar un encuentro antes de la reserva. Esta es una oportunidad para ver el entorno de la casa y conocer a las mascotas que viven allí
	    <span id="points3">...</span>
  
	    <span id="moreText3" style="display: none;"> tanto de manera virtual como presencialmente. En Doggy, recomendamos siempre, en la medida de lo posible, una primera aproximación para comprobar que el perro que vaya a ser hospedado esté cómodo y en el caso de que hubieran otros perros o mascotas su relación con la mascota a hospedar sea la adecuada.  </span>
	  <a onclick="toggleText3()" id="textButton3" class="link-dark read-more"> Leer más</a>
	</p>

      </div>


  <div class="p-2">
	<li><h5 class="font-weight-bold">¿Cómo puedo pagar una reserva?</h5></li>	
      </div>
      <div class="">
	  <p class=""text-justify>Una vez que hayas encontrado al cuidador perfecto para tu perro, Doggy hará que el pago sea sencillo. Aceptamos las principales tarjetas de crédito / débito
	    <span id="points4">...</span>
  
	    <span id="moreText4" style="display: none;"> para realizar el pago. En ese ello tendrán que contactor con nuestro equipo de Doggy por medio de esta misma web Aceptamos diversas formas de pago y por su propia seguridad recomendamos que la única manera de pago sea a través de esta plataforma. Si la reserva no se ha hecho por nuestra plataforma, no nos podremos responsabilizar de ella y no podremos resolver cualquier inconveniente o reclamo. </span>
	  <a onclick="toggleText4()" id="textButton5" class="link-dark read-more"> Leer más</a>
	</p>
      </div>

  <div class="p-2">
	<li><h5 class="font-weight-bold">¿Puedo cancelar una reserva?</h5></li>	
      </div>
      <div class="">
	<p class="text-justify">¡Sí, por supuesto! Entendemos que los planes pueden cambiar, por eso todas las reservas de Doggy tienen un reembolso del 100% en cualquier momento hasta 24 horas antes
	    <span id="points5">...</span>
  
	    <span id="moreText5" style="display: none;"> de el Check In. Para ello tendrán que contactor con nuestro equipo de Doggy por medio de esta misma plataforma por la sección de contacto o por el teéfono: 2323 3294 1233. Si el plazo de cancelación está cerca de cumplirse les recomendamos contactar a través del teléfono para evitar la demora del contacto vía texto. Nuestro horario de atención es de lunes a viernes de 9h a 18h. En caso de querer cancelar la reserva fuera de horario les recomendamos utilizar el mail al que responderemos a la brevedad. </span>
	  <a onclick="toggleText5()" id="textButton5" class="link-dark read-more"> Leer más</a>
	</p>
      </div>
</ul>
  
  
<p><a href="#">Lee más Preguntas Frecuentes (FAQ) en nuestro Centro de ayuda</a></p>
  </div>
   {% endblock %}

homepage/templates/homepage/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark" id="mainNav">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"
      ><img src="{% static 'img/logo.png' %}" alt="..."
      /></a>
      {% if user.is_authenticated %}
      <div class="bg-dark text-light text-uppercase ms-4 ">
        <a class="nav-link" href="#services"><i class="fa-solid fa-user me-2"></i>{{user.username}}</a>
      </div>
     {% endif %}
 <!--   <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarResponsive"
    aria-controls="navbarResponsive"
    aria-expanded="false"
    aria-label="Toggle navigation"
    >-->
     <button
    class="navbar-toggler cerrar"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarResponsive"
    aria-controls="navbarResponsive"
    aria-expanded="false"
    aria-label="Toggle navigation"
    >
    <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        {% if user.is_authenticated %}
         
          
          {% if 'Cuidador' in role %}
	     <li class="nav-item">
	       <a class="nav-link" href="{% url 'sitter_list' %}">Ver otros cuidadores</a>
            </li>
        
            <li class="nav-item">
	      <a class="nav-link disabled" href="{% url 'create_sitter' user.id %}">Convertirse en cuidador</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="{% url 'pet:register' user.id  %}">Registrar perro</a>
            </li> 
          {% endif %}  
          
          {% if 'Dueño' in role %}
	       <li class="nav-item">
	       <a class="nav-link" href="{% url 'sitter_list' %}">Buscar cuidadores</a>
            </li>
        
	  <li class="nav-item">
              <a class="nav-link disabled" href="{% url 'create_sitter' user.id %}">Convertirse en cuidador</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'pet:register' user.id  %}">Registrar perro</a>
          </li> 
	  {% endif %}
         
          {% if 'Invitado' in role %}
	       <li class="nav-item">
	       <a class="nav-link" href="{% url 'sitter_list' %}">Buscar cuidadores</a>
            </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'create_sitter' user.id %}">Convertirse en cuidador</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pet:register' user.id  %}"
            >Registrar perro</a>
          </li>
          {% endif %}  

            <li class="nav-item">
              <a class="nav-link" href="{% url 'send_email_help' %}">Ayuda</a>
            </li>
    
            
            
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ver perfil 
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'useraccount:editpro' %}">Editar cuenta</a></li>
            <li><a class="dropdown-item" href="{% url 'useraccount:password' %}">Cambiar password</a></li>
            <li><a class="dropdown-item" href="{% url 'useraccount:editprofile' user.id %}">Editar Perfil</a></li>
              
          </ul>
        </li>
        
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'useraccount:logout' %}"><i class="fa-solid fa-arrow-right-from-bracket pe-2"></i>Salir</a>
        </li>
        
        
        
        {% else %}
        
        
        <li class="nav-item">
          <a class="nav-link" href="#">Buscar cuidadores</a>
        </li>
       <li class="nav-item">
          <a class="nav-link" href="{% url 'useraccount:register' %}">Registrarme</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'useraccount:login' %}">Iniciar sesión</a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="#portfolio">Ayuda</a>
        </li> {% endcomment %}
        {% endif %}
      </ul>
    </div>
  </div>
 
<script>
  $(document).click(function (event) {

  /// If *navbar-collapse* is not among targets of event
  if (!$(event.target).is('.navbar-collapse')) {

    /// Collapse every *navbar-collapse*
    $('.navbar-collapse').collapse('hide');

  }
}); 
</script>
  <script src="https://kit.fontawesome.com/ef04847ec0.js" crossorigin="anonymous"></script>
</nav>